### ISSUE TITLE
people search: how do I find someone from a specific agency?

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1101]
Maybe I'm missing something here.... I was looking up someone from NIST, so I typed the agency name into the search on the people page, doesn't seem to be narrowing my results much

![image](https://cloud.githubusercontent.com/assets/41906/10744686/0b47c482-7bf9-11e5-89c7-177843d4fe35.png)

**Comment by dhcole** [comment]
Search uses a full-text search across all of the data associated with a model (user, task, or project). the phrase NIST appears in lots of words, including admiNISTration, so it doesn't appear like much filtering is happening — most users have GSA as their agency, which includes NIST.

You can get a more specific result by making your search string more specific, such as `(NIST)`, which you'll see is mostly correct with one additional user who has (NIST) in their bio statement and another who has it in an interest tag. https://openopps.digitalgov.gov/profiles?search=(NIST)

To be more specific, you could search for the whole agency, which is pretty likely to return an accurate match: https://openopps.digitalgov.gov/profiles?search=DOC%20National%20Institute%20of%20Standards%20and%20Technology%20(NIST), unless some has the full and exact agency title and acronym in their bio statement.

If you wanted to be 100%, you could search for the JSON attributes of the string, `"type":"agency","name":"DOC National Institute of Standards and Technology (NIST)"`, but that's not the best looking at this point since we don't format the search bar. https://openopps.digitalgov.gov/profiles?search=%22type%22:%22agency%22,%22name%22:%22DOC%20National%20Institute%20of%20Standards%20and%20Technology%20(NIST)%22

**Comment by dhcole** [comment]
With that, do you see a next action here, or does that address the issue?

**Comment by LisaLNelson** [comment]
see issue #1456
