### ISSUE TITLE
admin API calls are slow

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1125]
We're getting NewRelic warnings on these...  yet another indicator that our admin area needs a bit of love
![image](https://cloud.githubusercontent.com/assets/41906/11036033/d5285864-86aa-11e5-870e-56f7ce48771f.png)

**Comment by dhcole** [comment]
Here's some more about the slowest of the admin endpoints:

<img width="503" alt="screen shot 2015-11-09 at 2 58 30 pm" src="https://cloud.githubusercontent.com/assets/170641/11044904/8b62c4c4-86f2-11e5-8c7f-00e97146d875.png">

<img width="519" alt="screen shot 2015-11-09 at 2 59 39 pm" src="https://cloud.githubusercontent.com/assets/170641/11044906/8db615d2-86f2-11e5-8b2e-6c92c82fbc17.png">

<img width="504" alt="screen shot 2015-11-09 at 3 02 19 pm" src="https://cloud.githubusercontent.com/assets/170641/11044993/e628cd0e-86f2-11e5-9077-f4336533e5aa.png">

 
The user endpoint seems pretty fast, but it probably gets called a lot, so in aggregate seems more slow.

Otherwise, this report shows 0.5 - 2 seconds of load time on the admin user listing the admin task metrics.

The participants table takes the longest to load (up to 10 seconds). All of these tables load in the background with loading indicators presented to the users. They only affect the few admins we have. And since they're pulling nearly all of the data available in their respective tables, joined with associated records and tags, it seems acceptable that they're slow.

I raise all of this to see whether optimizing here is still a priority. There may be some easy fixes, but generally 2 seconds of loading for an admin table, or even 10 seconds for a table that is essentially a data export seems reasonable to me. It may be worth removing these endpoints from the New Relic alert, or setting a higher tolerance to catch endpoints completely stall out.

**Comment by dhcole** [comment]
Also, I included those endpoints in context of the whole list of transactions so it's easier to see how they impact the site as a whole.

**Comment by kbwagner** [comment]
3/27/18 - A lot of this was due to Sails and Waterline. Average response time now is like 33ms across the site.
