### ISSUE TITLE
Markdown tool: Header and List buttons don't work

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1166]
1) As a task creator it is not clear how to create a link.  I want to be able to highlight the words to be linked, click the link button, paste the URL and have it linked.

The multiple step process currently used dissuades people from linking.
2) From 1922: Many questions come in from Task Creators regarding how to link content as they do not understand Mark down language. We should replace markdown with something easier to use

Related ticket: 1868 spike to research.

From 3/26/19 Bug bash:
From 3/26/19 Bug Bash:
- When I type in "What You'll Do" and use the "bullets" in the wiziwig/markdown, it automatically gives me three 'bullets', but when I hit enter to type a fourth 'bullet', it doesn't automatically give you a bullet.

**Comment by rogeruiz** [comment]
Since the editor supports Markdown, links can easily be created using the following syntax:

```
[clickable link text here](http://example.com/their/url)
```

Which would generate this => [clickable link text here](http://example.com/their/url)

I'm thinking this can be easily tackled by prompting the user in the description above the editor for how to easily create links without adding any extra functionality. Maybe even a link to the official Markdown Syntax documentation [found here](https://daringfireball.net/projects/markdown/syntax). The prompt in the description could easily be copied, pasted, and edited a little faster than using the multiple steps we have now.

**Comment by Piglady64** [comment]
Fix the Header and List button in the markdown toolbox. You can use the markdown toolbox to create a link.

**Comment by raywilliams** [comment]
The header button had a typo that was corrected with code in the pull request.

The List buttons work as expected. If it automatically creates a new list item when you hit enter, you'd get trapped inside of list items. If you need to create more, you can click either list button again.

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-18-19 LHammond in testing

**Comment by kbwagner** [comment]
6/18/19 - KWagner tested in Chrome/Test

Ready for final reviwe
