### ISSUE TITLE
As a program administrator, I would like to see overview metrics for participation from my agency

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1256]
USDA, GSA OHRM and other agencies want to track the growth of Open Opportunities and associated employee engagement within their organizations. The dashboard would give agency program staff direct access to reporting data regarding tasks, people who have signed up, etc.

It is essential that we create a visually compelling experience that is also usable.  The ability for program administrators to effectively and easily report on their success is a key factor in allocating resources to the program, and also to inspire senior leaders and people across the agency to participate in outreach efforts.   Program administrators need to understand growth patterns in order to effectively manage the community and help it grow.

Overview Metrics:
- growth in membership & engagement: activity over time
  - members: users registering on the site
  - participants: users signing-up for an opportunity
  - opportunity creators: users who post tasks
- # of users by sub-group (for example: GSA by Service, USDA by Institute), showing relative proportions, like with a pie or bar chart
- task activity by sub-group (tasks created / task participation)

Navigation elements to get to different sections of the administrative experience showing:
- list of users
- list of tasks with agency participants
- activity stream
- agency configuration settings
- any chart should also have the option to export the data as a CSV

For the mockup, feel free to add forward-looking ideas that might not be implemented in the first release. For example, tracking repeat users is often requested, and data that we have "under the hood," but is not displayed on the current dashboard.

We will conduct some light usability testing with the mockups, which must address the following use cases:  As a program administrator, I can...
- see the number of tasks that were published in any year, quarter, or month, so that I can judge whether we need to do more outreach to task creators or judge the effectiveness of outreach, and also notice seasonal patterns
- see the number of tasks that are completed in any year, quarter, or month, so that I can see whether participation is steady, growing or declining and consider how to adjust outreach efforts to participants
- easily navigate to different areas of the admin console, to find lists of users and tasks, etc.
- see the same metrics that are available in the Open Opportunities global admin area, yet applied to my specific agency

**Comment by alwaysbrightblue** [comment]
As a reference, this is our current dashboard. We want to make it more appealing, and **count humans not tasks.**

![openoppsoriginaldashboard](https://cloud.githubusercontent.com/assets/2031438/13885459/e595436e-ed08-11e5-9815-42aa0230acf7.jpg)

**# References**

I immediately thought of financial tracking apps like Robinhood or the more traditional Fidelity. I see these as being useful for really drilling down into data and seeing reports in a graphically pleasing way. Here area  few screenshots of those apps for your reference:

![nexus2cee_robinhood6](https://cloud.githubusercontent.com/assets/2031438/13885522/43b0c108-ed09-11e5-9702-59065440ed96.png)
![robinhood-app-comparison](https://cloud.githubusercontent.com/assets/2031438/13885523/43b154e2-ed09-11e5-85fc-2387adc9edba.png)
![screen322x572](https://cloud.githubusercontent.com/assets/2031438/13885541/523d25ea-ed09-11e5-897d-fd864518e208.jpeg)
![screen480x480](https://cloud.githubusercontent.com/assets/2031438/13885542/523e65ea-ed09-11e5-8e89-1db2c8fe791f.jpeg)
![sharebuilder-ipad](https://cloud.githubusercontent.com/assets/2031438/13885543/523fabda-ed09-11e5-83aa-6eb68ccb5ed2.jpg)

**# Rough Mocks to start**
Showing humans, not tasks.
I broke this into three main views: Active Users, Interactions, Opportunities
## Active Users
I'm not sure if you guys can use the Google Maps API, but I think it would be helpful to see your humans in their geography to start rather than a list of things. To me, an agency head managing people all over the US should see _where and when_ at the same time. We view the latest achievements on a map, with the scope of time defaulting to 3-4 weeks until there is significant usage to reduce this number. There should probably be a filter for time for admins.
![a 1_open-opps-dashboard-mockup](https://cloud.githubusercontent.com/assets/2031438/13886106/cc2a734c-ed0b-11e5-873c-a2d70f7d8a74.jpg)
Hover over the image, you get a detail.
![a 1 1_open-opps-dashboard-mockup](https://cloud.githubusercontent.com/assets/2031438/13886108/cc2cd484-ed0b-11e5-88f8-2609d4935aa4.jpg)
Detail close up.
![a 1 1_detail_open-opps-dashboard-mockup](https://cloud.githubusercontent.com/assets/2031438/13886107/cc2b1d2e-ed0b-11e5-9186-a3b94a652561.jpg)

**Alternative view: List**
Not everyone may like the map, so an alt view is to just take the existing activity feed.
![a 2_open-opps-dashboard-mockup](https://cloud.githubusercontent.com/assets/2031438/13886239/6b8a88f0-ed0c-11e5-9b65-1b65dadf758f.jpg)

## Interactions
I think this where more people will want to drill down for data and where we pull influence from Robinhood and other financial planning apps.
![b 1_open-opps-dashboard-mockup](https://cloud.githubusercontent.com/assets/2031438/13886280/9ef6bd62-ed0c-11e5-982e-2a90f8cab086.jpg)

## Opportunities
Similar layout to accomplishments. We want to see who is posting and where they are. Hover over the image, you get a detail. Maybe you can drill down further to see the post, see other opportunities this person has posted or see how many opportunities this person has participated in. This is similar to the Wordpress plugin authors metrics, or a profile on Kickstarter.
![c 1_open-opps-dashboard-mockup](https://cloud.githubusercontent.com/assets/2031438/13886353/e1a501be-ed0c-11e5-9f9c-bb4a98178149.jpg)
![c 1 1_open-opps-dashboard-mockup](https://cloud.githubusercontent.com/assets/2031438/13886355/e1a8a6f2-ed0c-11e5-96cc-ce187bacaba0.jpg)
![c 2_open-opps-dashboard-mockup](https://cloud.githubusercontent.com/assets/2031438/13886354/e1a760e4-ed0c-11e5-83eb-aaf2eb7f1e96.jpg)

**Example Wordpress plugin author metric:**
![screenshot 2016-03-18 13 25 54](https://cloud.githubusercontent.com/assets/2031438/13886390/035b315c-ed0d-11e5-8507-8d587dba36c6.jpg)
**Example Kickstarter Profile:**
![screenshot 2016-03-18 13 27 02](https://cloud.githubusercontent.com/assets/2031438/13886418/229eae68-ed0d-11e5-86c2-d2a3e37de251.jpg)


I hope this helps get the conversation rolling.

**Comment by ultrasaurus** [comment]
@alwaysbrightblue so helpful to have some visual reference for brainstorming new directions here.  I particularly love your pencil sketch navigation -- made me realize how big a need re-thinking the admin nav is, so I've updated the issue description to include that.

We're working on getting some more design effort on this...  Thank you so much for pitching in!

**Comment by ultrasaurus** [comment]
We've created a design repo, and latest mockups for this are posted here: https://github.com/18F/openopps-design/tree/master/mockups/admin
