### ISSUE TITLE
guidlines for open source governance

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1287]
There's a lot of interest in this platform from state and local governments, as well as from other countries, and non-profit orgs.  Also, we have an active community in the federal government that is now focused on a single instance of the service that will be shared across US federal agencies.

We'd like to create a core team that could span private and public sector to provide technical and product guidance as the platform moves forward, including supporting new contributors by being responsive to pull requests and questions/discussion via email group, public slack channel and whatever other communication channels make sense.

@NoahKunin reports that we can broaden the core team to include non-18F folk as long as we have clearly documented guidelines that are fair and open.  

What should be our criteria for someone joining (and staying on) the core team?

Requirements:
- Follow the 18F Code of Conduct
- Active in some way...

**Comment by ultrasaurus** [comment]
@rogeruiz @jeremiak @csarsam @sefk @polastre @DavidEBest @Chessen @LisaLNelson @alwaysbrightblue @dhcole  -- interested in your thoughts since you have been active at various points.  Even if you don't have time to be on the core team, would love your ideas on what the criteria / commitment should be.  Would love it to be inclusive of design & product leadership that doesn't necessarily involve code commits.

**Comment by alwaysbrightblue** [comment]
Thanks for tagging me in this. I will think about this a bit. I would love to have been more involved over the past year, but I'm always juggling getting work/paying bills which puts this project on my back burner. Commitment requirements for someone like me would have to be considerate of paying work. I will think about this further...

**Comment by ultrasaurus** [comment]
I think in the near term there are a number of prospective core team members who would need a light time commitment, but the project would definitely benefit from having periodic input from people who have been familiar with how it works over a period of time and contributed in the past...  over time we could increase expected time commitment if/when the core team grows

**Comment by Chessen** [comment]
Sarah- I don't have a lot of experience with open source projects, but we did face some of these challenges using a volunteer/part time/distributed team when we first started this. I think the key requirement initially is that people are _responsive_ and _consistent._ Core team members can contribute 5 hours a week or just drop in every month to scan and contribute advice. But it should be regular. And they need to be responsive to reasonable requests for inputs. There is nothing more frustrating than someone who takes a piece of work or starts shaping an idea, people jump on board, start asking questions, need guidance, etc, and then the originator disappears and neglects the process.

**Comment by DavidEBest** [comment]
I'm up for helping out in some capacity, and could dedicate some small number of hours (2-3?) hours a week to supporting the project. I've also reached out to Code For America - this seems like something that could be useful for brigades.

**Comment by afeld** [comment]
A couple of examples where 18F has given write access to non-staff/Partners:

* https://github.com/18F/analytics-reporter
    * @laurenancona works for the City of Philadelphia, and became a contributor because they needed to make some modifications to it to make it more reusable.
* https://github.com/fisma-ready
    * This started before my time, so not sure of the backstory.
* https://github.com/opencontrol
    * @joshuamckenty started the org, but then invited a bunch of 18F people (and others). We ended up transferring [Compliance Masonry](https://github.com/opencontrol/compliance-masonry) there from the 18F org so that we could more easily collaborate.

Someone please correct me if I have those stories wrong!

My understanding is that someone outside of 18F starting a shared organization makes things easier, because then we are contributing to a shared project, rather than giving someone else access to "government-owned" things.

> we can broaden the core team to include non-18F folk as long as we have clearly documented guidelines that are fair and open

Nice! Sounds a lot like what we figured out for 18F's public chat rooms.

> new contributors

What are we talking about, more specifically? Decision-making power? Write access to this repository?

> What should be our criteria for someone joining (and staying on) the core team?

I haven't set up any formal governance structure in the past, but seeing as this project is relatively small (compared to a framework or an operating system or something), I think it can be something a bit fuzzy like "has actively participated in the community and/or contributed to the codebase regularly for at least two(?) months, and has been responsive to communications". I bet @brittag would have good ideas here.

**Comment by DavidEBest** [comment]
http://oss-watch.ac.uk/resources/governancemodels seems like a treasure trove of info on defining a governance policy. It includes several example real-world governance models, as well as some templates.

The big question for me is: What sort of model is intended for this project? Is 18F running the project with the intention of supporting the Federal instance of the platform, or is the goal to generally improve the platform (based on the community’s definition of improve)?

It was mentioned elsewhere by @jeremiak, but https://medium.com/the-javascript-collection/healthy-open-source-967fa8be7951#.1cibx7pzb is a good breakdown of the process the Node community has in place now.

> 
I think it can be something a bit fuzzy like "has actively participated in the community and/or contributed to the codebase regularly for at least two(?) months, and has been responsive to communications".

If someone asks (or is nominated) to join the core team, qualitative metrics are preferable to quantitative ones, especially if you'd like to get a breadth of experience (devs, designers, users, etc.) instead of just those comfortable with writing code and issuing PRs.

I also haven't set up a formal governance structure before, but find this fascinating. I'd love to help flesh out the details.

**Comment by joshuamckenty** [comment]
I *have* set up a formal governance structure for open source (several times), and it’s a dangerous tar pit. What is the problem you’re hoping to solve?

**Comment by ultrasaurus** [comment]
Great question @joshuamckenty -- here's my summary of the problem we're hoping to solve:

We're anticipating that we might have some periods of low staffing / funding from the US Gov, but want to support a thriving community of federal workers who use the platform with volunteer coders who are willing to help move things forward.  Also there is a lot of interest from other governments -- other countries, as well as US State and City governments, as well as some non-profits.  We can't always justify federal worker time to support those initiatives, but we all want to create a space to make that happen.  Gov budgets are small for this kind of thing, but there seem to be a few civic-minded folks willing to help!

So.. we're hoping to set up something where we can have a core group of committers who span public and private sector and aren't subject to the whims of congress and federal budgets in order to give the software the attention it deserves.  

I'm thinking something closer to bazaar than cathedral (see Eric Raymond's [famous essay](http://www.unterstein.net/su/docs/CathBaz.pdf)), but with enough peer-review (with guidelines for testing and what-not) that we feel we're keeping our civil servants and other users protected and supported.  That said people who are actively using this software are some of the most innovative civil servants and many are co-creators — we want to figure out guidelines where some of them will be on our core team!

Very interested in people's thoughts about what kinds of governance models will help us move towards these goals.

**Comment by joshuamckenty** [comment]
I'm going to be heretical for a moment.

I have seen almost all attempts at "meritocracy" fail in one of two ways:

First, they fail by becoming a hegemony - those who are already *on* the core team (and therefore have "merit") are in charge of defining "merit", and it always leads to increasing the number of folks who are just like they are. This is the typical trap for communities who use the "Apache Way" model of voting from existing core team members. (IMO, this is where we went wrong with OpenStack very early on.)

The second trap emerges when you try and avoid the first trap - when the community is TOO inclusive, eventually you accept a truly antagonistic individual into the core, and they poison it. Reasonable-thinking and hard-working individuals gradually give up and leave, and you're left with a community of the self-righteous and bitter, who become more and more satisfied with the increasing alienation they've achieved from the rest of their potential community.

Weirdly, the most healthy communities I've been involved in are almost always the "Benevolent Dictator" variety - because an overworked dictator is extremely likely to delegate to the folks who are actively helping out, and because they have the necessary authority to eject parasites. Yes - the culture of these communities will tend to mirror the culture of the BDFL (which is known as the Linux-Has-Lousy-UI-Because-Linus problem) - but at least they're FUNCTIONAL.

So if you're looking for a stable group of actual contributors, practicing code-review - I'd name yourself BDFL and move forward. 

If you want the best of the alternative (e.g., an egalitarian meritocracy that's at least reasonably defended against the violence of good intentions), I would recommend looking at C4.1. 

http://rfc.zeromq.org/spec:22

We made a number of experiments in both the OpenStack and CloudFoundry communities (as well as OpenQuake and, long ago, Mozilla) around inclusion of non-coding contributors, but unfortunately they mostly worked by trying to force everyone to use coding tools in their workflow (source control, review tools, backlog trackers, etc). I wrote a rant about this at https://gist.github.com/joshuamckenty/6242935 and Sean Roberts (then at Yahoo!) did some work on measuring "mentorship" as a key activity. More experiments are needed here.

**Comment by ultrasaurus** [comment]
thanks for the feedback @joshuamckenty -- we drafted up a modification of the "benevolent dictator" model: https://github.com/18F/openopps-platform/pull/1316/files

Still needs review from @NoahKunin and other 18F'ers to make sure it's all in keeping with whatever is needed for the government!

**Comment by joshuamckenty** [comment]
Cool!
