### ISSUE TITLE
As an admin, I do not want task creators to be able to open tasks.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1295]
Right now any task creator can Open a task.  That needs to change so all tasks get submitted to the admin for review and then the admin publishes when ready.

This is an example.
![screen shot 2016-04-14 at 12 17 13 pm](https://cloud.githubusercontent.com/assets/9039852/14535457/f2e1894a-023b-11e6-860b-bcc5d3c91ba0.png)

**Comment by rogeruiz** [comment]
We _might_ have this already in the User model, https://github.com/openopps/openopps-platform/blob/dev/api/models/User.js#L37-L41.

```
    // User is an admin for their agency
    isAgencyAdmin: {
      type: 'BOOLEAN',
      defaultsTo: false
    },
```

**Comment by mtorres253** [comment]
This is a feature that needs more detail. Will discuss with OHRM and document

**Comment by mtorres253** [comment]
For full-time details, it needs to go through classification review before being published. Anything that is GSA only would come to OHRM for approval. Admins can delegate approval authority to others. We should check into the share functionality to make sure it's working. Let's make sure that this works so that we can share opportunities with classification via email, so that they can get approval from classification before posting.
