### ISSUE TITLE
Identify team who will take over project after hand-off

### ISSUE THREAD

**Issue by mtorres253** [openopps/openopps-platform#1443]
We need a team of developers that are familiar with 
## Languages, tools, applications, etc.
- Node.js v4.2.2 (SailsJS)
- npm
- BackboneJS
- PostgreSQL - via Amazon RDS
- Redis - session store
- S3 bucket: photos & attachments
- Cron - AWS infrastructure Data Pipeline
- Shell for CI / CD
## Services: need accounts on all these things
- CloudFoundry / Cloud.gov experience / knowledge
- NewRelic
- Travis CI
- Github.com
- Cloud.gov (Cloud Foundry) - including an S3 bucket, Redis, DNS
- cf-shh 
- Mandrill (via MailChimp) for Email notifications - set up under devops@gsa.gov account 
- MyUSA authentication (OAuth2) - **this will change to some other authentication method**
- Web, mobile, or core SW languages (Java, Python, etc.)
- Open source - public code via GitHub (mirroring to Cloud.gov)

We need this team as soon as possible so that we can start knowledge transfer.

This issue is to track progress on this task

**Comment by mtorres253** [comment]
@acolter @LisaLNelson Lisa and I discussed today and identified a potential risk that OPM won't assign a team unless/until they delegate ATO authority to 18F. Let's discuss in tomorrow's meeting and come up with a strategy

**Comment by rogeruiz** [comment]
I will edit this as much as I can before EOD.

# Open Opportunities Platform Knowledge & Experiences

The Open Opportunities ( OpenOpps ) platform is a web application running on
both the client-side and server-side using separate MVC frameworks to manage the
state of the application. Most of the interactions occur on the client-side, so
this is a perfect **project for someone who is very knowledgable with client-side
JavaScript and either curious or knowledgable in server-side JavaScript.**

## Requirements

These are knowledge or experience criteria in order to be able to work with the
application.

### Languages

- NodeJS v4.x.x
- npm v3.x.x
- JavaScript, es6 / es2015
- Shell

### Frameworks

- Sails, Express, or Rails MVC framework experience
- Backbone, jQuery, Event driven

### Infrastructure

- CloudFoundry via [cloud.gov](https://cloud.gov)
- AWS, S3 specifically

### Databases

- PostgreSQL
- Redis

## General Requirements

These are certain specific knowledge that would be make it very easy to work on
this project.

- Troubleshooting
- Browserify and transforms
- Grunt or gulp automation
- Travis / Circle CI experience

**Comment by mtorres253** [comment]
Looks like it's still going to OPM, but there is noone to develop features at this moment. @LisaLNelson and @acolter are working on it. Team will not be identified by end of engagement.

**Comment by LisaLNelson** [comment]
OPM is lead contributor as part Open Community.
