### ISSUE TITLE
Test Server Gives 404 API Error

### ISSUE THREAD

**Issue by sshadmand** [openopps/openopps-platform#1497]
When accessing a link on https://pages.18f.gov/openopps-platform/ I get the following 404 error:

<img width="619" alt="screen shot 2016-11-21 at 1 23 00 pm" src="https://cloud.githubusercontent.com/assets/68735/20495085/abf2abee-afed-11e6-8de1-c40fdb733582.png">

https://cl.ly/3N0n2L2l1x1N

**Comment by LisaLNelson** [comment]
The community test server link is dead on the README.md page. As an admin I need this to be fixed so that the community has an opportunity to participate in the testing process and provide feedback. The message I get is. 

![screen shot 2017-08-05 at 11 24 12 am](https://user-images.githubusercontent.com/9039852/28996540-ae2a8e4c-79d0-11e7-8d93-f62574104b80.png)

**Comment by lawrencek76** [comment]
Resolved with #1536
