### ISSUE TITLE
Sporatic timeouts starting app in Cloud.gov

### ISSUE THREAD

**Issue by qquinn** [openopps/openopps-platform#1528]
Errors from the CF logs are below. Short term - try increasing sails global hook timeouts. Long term - disable grunt in production? 

```
2017-08-22T00:32:25.76-0400 [APP/PROC/WEB/1] OUT Loading...  /home/vcap/app/config/email.js
   2017-08-22T00:32:26.21-0400 [APP/PROC/WEB/1] OUT Loading...  /home/vcap/app/config/version.js
   [31m2017-08-22T00:32:42.73-0400 [APP/PROC/WEB/0] ERR Error: The hook `grunt` is taking too long to load.[0m
   [31m2017-08-22T00:32:42.73-0400 [APP/PROC/WEB/0] ERR Make sure it is triggering its `initialize()` callback, or else set `sails.config.grunt._hookTimeout to a higher value (currently 20000)[0m
   [31m2017-08-22T00:32:42.73-0400 [APP/PROC/WEB/0] ERR     at Timeout.tooLong [as _onTimeout] (/home/vcap/app/node_modules/sails/lib/app/private/loadHooks.js:85:21)[0m
   [31m2017-08-22T00:32:42.73-0400 [APP/PROC/WEB/0] ERR     at ontimeout (timers.js:386:14)[0m
   [31m2017-08-22T00:32:42.73-0400 [APP/PROC/WEB/0] ERR     at tryOnTimeout (timers.js:250:5)[0m
   [31m2017-08-22T00:32:42.73-0400 [APP/PROC/WEB/0] ERR     at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by ultrasaurus** [comment]
noticing in the [Aug 16 Cloud.gov Update](https://cloud.gov/updates/2017-08-16-release-notes/) that they upgraded some of their software.  On the new [app maintenance page](https://cloud.gov/docs/getting-started/app-maintenance/) they recommend restaging the app to keep it up to date.  

You should try that, and then if that doesn't fix it.  Please file a ticket with cloud.gov, since it seems like there may be an issue with the platform.

**Comment by quadrinaquinn** [comment]
thanks for the update! Lisa mentioned the same thing today so hopefully that's the issue! I did restage the app on Monday when we were troubleshooting but it didn't seem to help at the time.

**Comment by kbwagner** [comment]
Fixed when platform was stabilized.
