### ISSUE TITLE
Locations: Standardize to avoid duplicates.

### ISSUE THREAD

**Issue by KatMullens-work** [openopps/openopps-platform#1710]
As a user, I want to have a single list of locations to choose from when I am creating my account (or any other place where it asks for a location).  If my city is not present, I want to be able to add it.
![image](https://user-images.githubusercontent.com/25315047/36054642-8eb90988-0dc5-11e8-8fa4-9356e2833449.png)

Adding from Release 2 bug bash:
- Should consider using USAJOBS location table 
- Allow for entry of state acronyms
- tell user what we are looking for city, state, or street address

**Comment by bmcorum** [comment]
@KatMullens-work, so the issue here is that there was a bug in the logic that was causing the same location to be inserted multiple times. If you notice at the top of the list there is a "search for list location" which does a lookup and returns a list of possible matches from GeoLocations. Upon selecting a location from the lookup list we are not double checking against the database to make sure we don't already have a matching/duplicate record before creating a new location record.

**Comment by KatMullens-work** [comment]
Hi @bmcorum : Can we use the same mechanism as USAJOBS for locations?

**Comment by KatMullens-work** [comment]
Also: if we move away from GeoNames that we should remove that link in the OpenOpps footer.  Because we use GeoNames now we're supposed to "credit" them is what we were told so we left that link in the footer.

**Comment by kbwagner** [comment]
We need to remove duplicates and also prevent duplicates from occurring again in the future.

**Comment by kbwagner** [comment]
7/25/19 - Kwagner - Closing - we use USAJOBS location table now
