### ISSUE TITLE
As a developer, I would like a single place where db connection configuration is loaded

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1740]
My guess is that the db configuration refactor is not yet complete.  Currently we have two places in the code where db configuration is specified:

1. `config/connections.js` has a lot of references to sails, so I suspect that is old and should be deleted; however it is still used by `tools/lib/dbTools.js`
2. `db/index.js` seems to be the new configuration in use by the app
3. `database.json` - not sure where this is used

Discovered this while attempting to reproduce https://github.com/openopps/openopps-platform/issues/1739 locally

**Comment by bmcorum** [comment]
@ultrasaurus, db/index.js is not a config file. It is what establishes the database connection for the application. It first attempts to read from cloud foundry otherwise it assumes local development.

**Comment by bmcorum** [comment]
@ultrasaurus, we are not currently using a config file for db-migrate since it will use process.env.DATABASE_URL by default if it is found, and CF builds this for us by default. If you are using something other than Cloud Foundry that may be why you are having issues.

https://db-migrate.readthedocs.io/en/latest/Getting%20Started/configuration/#database_url

https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#DATABASE-URL

**Comment by ultrasaurus** [comment]
correct.  I am attempting to address https://github.com/openopps/openopps-platform/issues/1560 and document how to set up an instance on AWS.

It is unexpected that [db/index.js](https://github.com/openopps/openopps-platform/blob/dev/db/index.js) has a hard-coded default db config.  I think `openopps.dbConnection` is always undefined.  

I was thinking that it might make sense to load `database.json` in `db/index.js`
