### ISSUE TITLE
Optimize No Search Results Page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#1966]
### Who 
Open Opps Users 

### What
Mirror the USAJOBS no search results page with helpful links to help content, etc.

### Why
As an Open Opportunities seeker, I want to be able to understand how to revise my search criteria to find better results

### Acceptance Criteria
Create a no search results page similar to the image below. Content is the following:

Header: Oops, we didn't find any results.  (note: mock has different title)
 
- Make sure you have at least one status filter applied to receive results.
- Check your spelling.
- Use more generic keywords or fewer keywords.

Learn more about how to search for an opportunity. (links to https://usajobs.github.io/openopps-help/opportunity/search/)

Have questions? Email the Open Opportunities team. (email goes to openopps@usajobs.gov)

### Mocks / Related Tickets
Note: use title from AC not mock
<img width="608" alt="Open-Opps_DOI_sketch" src="https://user-images.githubusercontent.com/11526811/73760110-ea221980-473a-11ea-910a-c7914181d237.png">

**Comment by kbwagner** [comment]
Info from Ticket 1842 which was closed as a duplicate of this ticket: As an Open Opportunities seeker, I want to be able to understand how to revise my search criteria to find better results

Revise Oops, we didn't find any results.

Mirror the USAJOBS no search results page with helpful links to help content, etc.
Entered from the 3/6/18 bug bash.

**Comment by kbwagner** [comment]
Current page: 
![image](https://user-images.githubusercontent.com/18709918/71996693-a22ad800-320a-11ea-897a-d60cfc4ee30d.png)

**Comment by nia-johnson** [comment]
@kbwagner What should this page look like content wise? I don't think Open Opps has the all the same functionality as USAJOBS, so we might have to add something else to the page if that is the case. Here's the following: 

- Keyword & Location - I think this is fine, especially once #2218 is picked up and goes to Prod
- Filters - This is fine 
- Profile - It doesn't seem like Profile content has much of an effect on opportunities coming up in search, so I don't think this should be here. 
- Save Search - It doesn't look like Open Opps has save search functionality. I can write a design ticket, if you want it added in. Otherwise, this shouldn't be here either.

**Comment by nia-johnson** [comment]
@kbwagner Never mind the above. Looked at the design ticket and adding those requirements in

**Comment by kbwagner** [comment]
@nia-johnson this looks good but we should definitely add bullets to each line.

**Comment by nia-johnson** [comment]
@kbwagner Done.

**Comment by kbwagner** [comment]
@nia-johnson the only thing I added here is where the link should go for learn more about how to search.  But done. Thanks.

**Comment by nia-johnson** [comment]
Moved to TFS: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/Atlas/_backlogs?level=Backlog%20items&showParents=false&_a=backlog
