### ISSUE TITLE
Opportunity Create - checkbox for limit participation automatically populates.

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2165]
Steps to Reproduce:
1) Create an opportunity
2) click on the Full Time Detail option under When
3) Click on One time or ongoing and now the Limit participation box is automatically checked. 
- Only happens once you have clicked on full time detail

5/15/18 - KWagner removed requirement for checkbox to be a radio button per discussion with Brice and Min.

**Comment by bmcorum** [comment]
@minchung12 I don't see the necessity of changing a checkbox to a radio button just because we disabled it. As far as a functional bug it has always operated as it does now and I don't recall any specific AC stating that its operation should change (meaning this is a function change request not a bug).

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/40070781-0e259f44-583d-11e8-8d7a-6cedad48bade.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by kbwagner** [comment]
5/15/18 - KWagner - Tested in Chrome and mobile. 
@LisaLNelson ready for final review.

**Comment by LisaLNelson** [comment]
approved
