### ISSUE TITLE
Admin Dashboard: Opportunities --> Manage sort by

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2389]
Who: All administrators
What: Add sort by to opportunity pages
Why: To allow administrator to find opportunities easily

Acceptance Criteria: 
- Add sort by to all Admin Dashboards for Opportunities --> Manage --> Opportunities page
1)  Sitewide
2) Agency
3) Community 

Sort by Options should include: 
Title - alpha A-Z
Creator - alpha A-Z by last name
Date - newest to oldest

Default sort will be date - newest

Related ticket: 2364 - Admin - Section 1 - Opportunities

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-16-19 LHammond in testing

**Comment by bmcorum** [comment]
@Kibrahacha67 we can discuss this with the PMO, but names for users who have not logged into OpenOpps since we implemented Login.gov is a guess at best since we are trying to break apart the full name and guess at last name. Title with non-alpha characters is also going to be near impossible to sort properly. Should non alpha be first or last? Here it appears to have ignored non-alpha characters and sorted correctly by ignoring the non-alpha characters.

**Comment by bmcorum** [comment]
@Kibrahacha67 there are some profiles in the system that have last names listed like 'K. Odor'. See list below of users with last names that may appear to be ordered incorrectly.

![image](https://user-images.githubusercontent.com/1165615/63284604-ecbeae80-c281-11e9-97ef-4b3aed409e35.png)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
8-21-19 LHammond in testing.

**Comment by kbwagner** [comment]
8/26/19 - KWagner tested in Test/Chrome
Ready for final review
