### ISSUE TITLE
Login.gov: Add/Change authentication to use OpenID Connect

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2420]
User Story: As an Open Opportunities user, I want to be able to use login.gov to allow me to have one login for USAJOBS and Open Opportunities.

Acceptance Criteria: 
- Add authentication via USAJOBS/Login.gov using OpenID Connect
- When the Open Opps user clicks on sign in, they will be taken to the Login.gov transition page specific to Open Opportunities
- USAJOBS will send and Open Opps will accept: doc ID (unique ID), federal email address, profile type (federal or student) (Claim)

**Comment by bmcorum** [comment]
- [ ] Login via Login.gov using USAJOBS profile
   - [ ] Happy route: Existing accounts, emails match
   - [ ] Unhappy route 1: Existing accounts, emails do not match
   - [ ] Unhappy route 2: New USAJOBS profile
   - [ ] Unhappy route 3: New OpenOpps profile 
- [ ] Display unauthorized access page: Not a federal employee
- [ ] Display please complete your profile page: Federal email not validated

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**NOTE:** You must have a USAJOBS profile in TEST. If your account it TEST is not marked FED with a validated federal email address you will get the unauthorized page. If you log into USAJOBS to update your profile to federal and validate your email you will need to log out of USAJOBS at this time to get updated claims before trying to sign into OpenOpps. This issue will have to be fixed in USAJOBS.

**Comment by Kibrahacha67** [comment]
8-20-18 LHammond in testing

**Comment by Kibrahacha67** [comment]
@bmcorum please attach artifact for #3 in the AC.

**Comment by bmcorum** [comment]
@Kibrahacha67 here is your artifact. Notice this is from login.test.usajobs.gov

Sub value is the documentID
HiringPath is the profile type

![image.png](https://images.zenhubusercontent.com/59e8ff8ea468affe6df75add/a52ff193-78d3-4332-9c6c-79d750fb3bcc)

**Comment by Kibrahacha67** [comment]
Testing completed moving to review.

**Comment by tlorrison** [comment]
Final approval
