### ISSUE TITLE
Create Unpaid Internship Community

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2646]
User Story: As an unpaid internship administrator, I want a community set up for the program so that we can better administer the work of the community.

Acceptance Criteria: 
The following information should be entered into the community attribute table for the unpaid internships:
•	Community Name: Student Internship Program (unpaid)
•	Agency: Department of State
•	Community Manager Contact Name:  Student Internship Program Office
•	Community Manager Contact Email: (if there are questions where to do they email?  Can be a group email box) The email would be studentinternship@state.gov 
•	Community Administrator: Khadijah Dargan
•	Description: 500 characters: The U.S. Department of State Student Internship Program is an unpaid internship with the opportunity to work in U.S. embassies and consulates throughout the world, as well as in various bureaus located in Washington, D.C. and at Department offices around the United States. This program is designed to provide substantive learning experiences in a foreign affairs environment.
•	Target Audience:  Student
•	Closed Group: Yes (only students can apply)
•	Community type: Program 
•	Community Related skills: leave blank
•	Opportunity Duration: Cyclical 
•	Microsite URL: provide the  Unpaid internship program home page link- https://careers.state.gov/intern/student-internships/ 
•	Support Contact: studentinternship@state.gov

**Comment by Piglady64** [comment]
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35503&fullScreen=false&_a=edit

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/49374921-d3180f80-f6d0-11e8-9574-c2c2a96ae857.png)
![image](https://user-images.githubusercontent.com/1165615/49374948-e0cd9500-f6d0-11e8-9151-b59abdc2be74.png)
![image](https://user-images.githubusercontent.com/1165615/49374963-eb882a00-f6d0-11e8-95c8-f6d04e40d369.png)

**Comment by Kibrahacha67** [comment]
12-7-18 LHammond - there are a few fields that are not on the AC that are not on the artifact.  If they are not in this table or not available at this time we need to document that they will be carried out at a different time to pass this ticket.  Below are the fields that are not represented in the screen shot.
• Closed Group: Yes (only students can apply)Should this have “yes” rather than a “t”?
• Community type: Program – (should we have “program” in this field rather than it blank?
• Community Related skills: leave blank (missing this field)

**Comment by bmcorum** [comment]
- Closed group is a boolean field (true/false). True (t) = yes, false (f) = no
- Community related skills is a many to one relationship and thus skills will be stored in another table, but since there are no skills there is nothing to show

![capture](https://user-images.githubusercontent.com/1165615/49876757-00ac3980-fdf2-11e8-9435-89053e1500c3.PNG)

**Comment by Kibrahacha67** [comment]
12-12-18 Moving to review

**Comment by kbwagner** [comment]
12/12/18 - Reviewed in Test. 
Ready for final review.
