### ISSUE TITLE
Create Approver role (Sitewide)

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3035]
Who: Administrators
What: Create a role for approving opportunities only
Why: in order to provide a role for someone who needs to be able to approve internships but shouldn't be able to manage users

Acceptance Criteria:
- Create a new sitewide role of Approver
- The approver will have the ability to manage opportunities (Sitewide) and click "Approve" only
- The approver will not be able to manage users

**Comment by bmcorum** [comment]
Ready for testing

**Comment by bmcorum** [comment]
![image](https://user-images.githubusercontent.com/1165615/72100357-784be100-32f0-11ea-83c8-137d0ee2f973.png)

**Comment by Kibrahacha67** [comment]
1-10-20 LHammond in testing

**Comment by bmcorum** [comment]
@Kibrahacha67 I am not sure there is much we can do about this because we are trying to display too many columns now.

@kbwagner how do you want handle this?

**Comment by bmcorum** [comment]
So after some additional research and discussion, we have simply run out of room on the page causing our table to be wider than the available space. Most browsers should create a scrollbar but this may not be easily noticed by users. My suggestion would be to see about a redesign for this page. Maybe a card style listing rather than just a straight table. Could have first line include basic details like name, agency, emails. Second line could include timestamps for created, last updated, last login. Last line would include the toggles for account enabled, sitewide admin, sitewide approver. This would also give us more room in the future to display additional user details by adding vertically on the page rather than continuing to add information horizontally on the page. @abudz19,  @kbwagner, @nia-johnson thoughts?

**Comment by Kibrahacha67** [comment]
Testing completed moving to review.

**Comment by kbwagner** [comment]
1/20/20 - KWagner tested in Chrome/Test
Ready for final review

**Comment by kbwagner** [comment]
1/20/20 - KWagner tested in Chrome/Test
Ready for final review
