### ISSUE TITLE
Reloading a page occassionally causes a blank screen

### ISSUE THREAD

**Issue by louh** [openopps/openopps-platform#307]
The specific ways to reproduce this is unknown, but several times I've attempted to reload the page and encountered a blank screen.

Here is one instance when I seem to be able to successfully reproduce:
1. Be logged in, and go to your profile page.
2. Click on "Edit Profile."
3. Now you're on the edit page. Reload this page. Blank screen!

**Comment by brendanwhitfield** [comment]
This may or may not be related, but I have received blank pages when openning new tabs. It appears to be a Firefox-only problem.

**Reproduce with Firefox 38:**
Open a link (anything, ex: the `Browse Working Groups` button) in a new tab. For me, this can be done via CTRL-clicking. This opens the tab in background, and when brought to the foreground, the tab is blank, and the DOM is empty. In these cases it appears as if the app never even started.

On the hunch that it was a startup problem, I moved the [`appr.initialize();`](https://github.com/18F/midas/blob/devel/assets/js/backbone/app.js#L62-L64) call inside of the jQuery onload function directly above. This solved the problem, but feels a little drastic. I'll see if I can tease out more details.

**Comment by brendanwhitfield** [comment]
It appears to be a race condition between the DOM and JS. jQuery selectors are returning empty and failing silently. While all the various `render()` functions are indeed getting called, they have no effect, since their root element's weren't selected.

Another remedy I've tested (besides to the one mentioned above), is to move the [bundle.js `<script>`](https://github.com/18F/midas/blob/devel/views/layout.ejs#L31-L36) to the bottom of the page, allowing the body elements to be parsed before execution.

**Comment by LisaLNelson** [comment]
No longer an issue
