### ISSUE TITLE
Department of State: Remove question from drawer

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#3178]
Who: Student
What: Length of overseas experience text box 
Why: This question relates to all of the overseas experience not just "other"

A/C
- On the Experience and Reference remove the "Please indicate the total length of your overseas experience(s)" from the drawer under "other"
  - This should be visible when the user selects "yes"  to the question "Do you have any overseas experience"  because it relates to all of the overseas experience . 

**No mock included"

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
3-26-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
@Piglady64 - question on this ticket. the following statement is only when the radio button for "do you have any overseas experience -- Yes.  IF the answer is No then the entire section is hidden.
"This should be visible at all times because it relates to all of the overseas experience in the previous question."

Please confirm prior to me completing the test as it is not visible at all times...

**Comment by Piglady64** [comment]
@Kibrahacha67 I am sorry, i wasn't clear in the A/C. The question should be presented when the student selects "yes". If they select "no" it will stay hidden. It is currently only being presented if the user clicks "other"

**Comment by Piglady64** [comment]
Julie tested in Chrome. Looks good. Moving to final approval
