### ISSUE TITLE
Mobile - Filters are not displayed properly

### ISSUE THREAD

**Issue by margaretdumas** [openopps/openopps-platform#3195]
The filters are not displayed correctly on mobile.  On the search page, the filter number displays "0".  When you click the "filter option, it shows "Filter 20 opportunities found.

Steps to reproduce:  
1.  On mobile device go to the search internship page
2.  Notice at the bottom of the screen the "Filter option displays "0"
3.  Click "Filter" to expand it
4.  At the top of the device "Filters  20 opportunities found" is displayed

Screenshot attached.  
![image.png](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/396688e5-a998-4cdc-9273-e26a443710ef)

![image.png](https://images.zenhubusercontent.com/59ef9329a468affe6df7fe8a/b611914c-d428-4636-b3e7-783f2179e379)

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
6-18-19 LHammond in testing

**Comment by Kibrahacha67** [comment]
@kbwagner Question, The search function for mobile "Internships" works a bit different from "Opportunities"  So when it loads there are no status here, so it loads all open internships without filters being applied.  In Opportunities since there are status "Open, Closed etc" those are counted as filters so the page will have pills and filters applied to get the right number of Opportunities in the system.  Question is are you expecting the behavior from Opportunities in Internships?  There is a problem with the filters in that once filters are added, the pills add but the count of filters is not being displayed.  I will put in a ticket on that one, but this ticket is working as is expected.  please let me know your thoughts as this will be on hold until we have information.

**Comment by kbwagner** [comment]
@Kibrahacha67 sorry I missed this question. This ticket itself is fine 

For internships, we only ever want to display Open...and because it's not a visible filter i don't think it needs to count as one.  Does that make sense?

**Comment by kbwagner** [comment]
6/24/19 - KWagner tested and this works fine on Apple mobile safari Test environment.
Ready for final review.
