### ISSUE TITLE
Bug: Admin delete of approved doesn't delete

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3322]
Environment: Test
Browser: Chrome

Steps to reproduce:
1) Admin --> Community --> opportunities --> Manage --> approved
2) Click on delete beside an approved opportunity.
- Add applicant functionality displays

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment]
4-17-19 LHammond in testing

**Comment by bmcorum** [comment]
@Kibrahacha67 upon further investigation I was able to determine why you could not delete that particular internship. It turns out that internship belongs to a cycle where the application start date as passed preventing it from being deleted. However in this instance it is also a submitted internship that was never approved and therefore should be eligible for deletion. I will communicate with the program office to get a requirement for deleting unapproved internships after the application start date as passed.

**Comment by Kibrahacha67** [comment]
4-17-19 Testing completed...moving to review.

**Comment by Piglady64** [comment]
I created a new cycle - created an internship opportunity - clicked Delete and the internship was deleted. moving to final approval.
