### ISSUE TITLE
Bug: Cycle date issues

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3471]
Environment: UAT and Test

Issue: 
- we are eastern time but all the cloud.gov servers are using UTC time
- JavaScript is trying to convert that to a datetime object so it is creating a date of 4/30/2019T00:00:00.000 which is 04-29-2019T20:00:00.000 EST
- The servers are getting time that is 4 hours different so the days all are off by one
- we are storing just the date without time

Resolution: 
- Resolve date/time issues between our eastern time requirements and cloud.gov 

Steps to reproduce:
1) Create a new cycle with an apply end date of today
2) Post an internship for the new cycle - it will not display

**Comment by bmcorum** [comment]
@margaretdumas and @Kibrahacha67 see attached artifacts.

UTC offset for eastern timezone is 4 hours for standard time and 5 hours for daylight savings. Since our dates are stored as UTC in the database we add +4 or +5 hours so that when pulling UTC it converts back to the start of the listed day at 00:00:00.

Example: 2019-05-01 04:00:00:00+00 UTC -4h = 2019-05-01 00:00:00 EST 

![image](https://user-images.githubusercontent.com/1165615/57039785-9b83a400-6c2b-11e9-90cb-2d0ce0fdabfd.png)


![image](https://user-images.githubusercontent.com/1165615/57039592-15fff400-6c2b-11e9-8789-ab7eee9f1cc9.png)

**Comment by Kibrahacha67** [comment]
5-2-19 LHammond in testing.

**Comment by kbwagner** [comment]
5/6/19 - Reviewed artifacts.
Ready for final review.
