### ISSUE TITLE
Spike: Research changing communities

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3529]
Research related to 2838 - changing a community
- Federal vs student communities
- Changing to a community I'm not a member of or between agencies?

**Comment by bmcorum** [comment]
## There are two flows for consideration.

#### Creating a new opportunity or internship
- [ ] **Option 1:** If wrong community was selected the user can click cancel which return to the target audience selection page. This will result in data loss since no data has been saved at this point.

- [ ] **Option 2:** Display selected community on form with a change link or button. Clicking change will prompt user (modal) to select new target audience and community. This will result in data loss if target audience changes.

#### Editing an existing opportunity or internship
- [ ] **Option 1:** Display community selection on view page with a change community link or button. When clicking change link prompt user (modal) with message that changing community may result in some information being lost and provide them with the ability to select new target audience and community. Clicking change community on prompt will trigger conversion process. Successful conversion will present the user with the proper form to fill out any required fields and provide any additional missing information.

- [ ] **Option 2:** User must click edit link on view page and once taken to the form, display selected community on form with a change link or button. When clicking change link prompt user (modal) with message that changing community may result in some information being lost and provide them with the ability to select new target audience and community. Clicking change community on prompt will trigger conversion process. Successful conversion will present the user with the updated proper form to fill out any required fields and provide any additional missing information.

**Comment by bmcorum** [comment]
@margaretdumas or @Kibrahacha67 would you please review my comment above for sanity?

**Comment by abudz19** [comment]
@bmcorum Sounds fine to me.

**Comment by Kibrahacha67** [comment]
I would agree, allowing changes within target audience would allow us to keep data integrity.  Process integrity would also be maintained, so no confusion on internship opportunities crossing lines with other opportunities and visa versa.

**Comment by kbwagner** [comment]
6/4/19 - KWagner reviewed
- will work on updating 2838
