### ISSUE TITLE
Spike Bug: Firefox login takes user to USAJOBS instead of Open Opps

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3579]
Environment: Test
Browser: Firefox (tried version 66.0.3 and 63.0.3) on and off network

Steps to follow:
1) Open Firefox
2) Navigate to openopps.test.usajobs.gov
3) Click sign in
- sometimes there is an issue right here where it takes you to USAJOBS other times you get to login.gov page
4) On login.gov page, enter password and code
5) you are taken to your USAJOBS profile

**Comment by bmcorum** [comment]
Issue appears to be during the POST event to usajobs.gov/Transition page. Where the user is being redirected to usajobs.gov rather than Login.gov

![image](https://user-images.githubusercontent.com/1165615/60269577-bd607680-98bc-11e9-90c0-d3f7328491d6.png)

![image](https://user-images.githubusercontent.com/1165615/60269543-a7eb4c80-98bc-11e9-9182-1bf8404e06f1.png)

**Comment by kbwagner** [comment]
Related TFS ticket:  36778

**Comment by Kibrahacha67** [comment]
Moving to review

**Comment by kbwagner** [comment]
I will place a hold tag on this and leave it in test so we can keep track of the TFS ticket which I believe will be moved into the next sprint.

**Comment by kbwagner** [comment]
7/17/19 - KWagner tested in Firefox/Test
- tested logging in 3 times and every time took me to Firefox and not USAJOBS
- Logged in as student and fed

Ready for final review.
