### ISSUE TITLE
Don't send opportunities back to submit status when edited

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4284]
Who: Opportunity creators
What: Don't send opportunity back to submit status if approved and then edits are made
Why: to avoid confusion and rework

Acceptance Criteria:
- For regular opportunities (no change for students), if an opportunity is edited after approval, do not send back to submit status when edits are made.

**Comment by raywilliams** [comment]
No changes made. Ready for testing.

**Comment by kbwagner** [comment]
@raywilliams I just tested this for a regular opportunity and it still sends it back to submit status if I make an edit and it's been previously approved.

**Comment by Kibrahacha67** [comment]
12-31-19 LHammond in testing
changes to all fields except two, will produce the correct action.  The opportunity will stay in open  status.  But if you update from Virtual to In Person, the form will save in submitted status.  If this is correct then send it back to testing otherwise sending to development.

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/693bd52f-f042-46d5-b109-1f262f91c5df)

![image.png](https://images.zenhubusercontent.com/5aa2e8314b5806bc2bca392c/2d604eca-ab66-4d65-b948-d8fbc28a343a)

**Comment by kbwagner** [comment]
@raywilliams @Kibrahacha67 when I tested I changed the What you'll do field and saved and it went back to submit.  
- For the regular opportunities, there is no field change that should send it back to submit status once approved

**Comment by Kibrahacha67** [comment]
Good then we are on the right track...thank you

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-7-20 LHammond in testing

**Comment by kbwagner** [comment]
1/9/20 - kWagner tested in Chrome/Test
Ready for final review
