### ISSUE TITLE
Add Search by community to signed in landing page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#4369]
Who: Open Opportunities Users
What: Add search by community to signed in landing page
Why: To allow users to search by communities from the landing page

Acceptance Criteria:
- Add Search by Community
- This should be the first column on the left and others will shift to the right
- Show the top 5 communities based on who has the most posted first to last
- Don't display a community that has no opportunities 
- The Student Internship community should not display
 
Current Site:
![image.png](https://images.zenhubusercontent.com/59ee08f1a468affe6df7cd6f/825b0d24-5a43-4b9d-8a37-7b3f61a5a235)

**Comment by bmcorum** [comment]
Ready for testing

**Comment by Kibrahacha67** [comment]
1-29-20 LHammond in testing
Testing completed moving to review.
NOTE: in the search from the home page, there is one community that will bring back 0 results on the surface.  but in fact it has one opportunity in the completed state, and since the search only brings back Open results it brings back a null.  May want to consider adding ticket to tighten up search criteria for this search set.

**Comment by kbwagner** [comment]
@Kibrahacha67 yep I was about to send it back when I saw your note.  I'll put in a ticket to only display if status is Open
