### ISSUE TITLE
Search for groups filters uses "and" while opportunities uses "or"

### ISSUE THREAD

**Issue by nhu313** [openopps/openopps-platform#801]
As a user, I find it confusing that the group and opportunities filter differently. (Is this how it is suppose to be?)

Steps to reproduce:
1. Click "Browse Working Groups"
2. In the search box, enter "test"
3. Note there are 3 search results
4. In the search box, enter "group"
5. Note now there is only 1 result
1. Click on "Browse Opportunity"
2. In the search box, enter "app"
3. Note there are 2 results
4. In the search box, enter "USDA"
5. Note there are still 2 results
6. Remove the "test" filter so you'll be left with only "USDA" filter 
7. Note there is only one result

**Comment by brandtheisey** [comment]
@nhu313 ! Thanks for the the bug report, I'm looking at it now.

**Comment by brandtheisey** [comment]
This is due to what search is doing under the hood.

Basically there is a freetext search and a tag search run for searches and the results are returned together. Freetext is **and'ed** and tag search is **or'ed**.

So depending on what matched you will see the described behavior. Further, when you remove a term from the list you may see the result set grow because now the **and'ed** freetext matches things that were excluded before. This can be non-obvious with Working Groups/Projects because tags aren't displayed on the Browse Working Groups/Projects page.

**Comment by GailSwanson** [comment]
We need to make wether they act as an 'and' or an 'or' clear to folks. It's pretty standard that tags operate with an 'and' model because of the ubiquity of ecommerce faceted navigation patterns. Freetext search is less consistent and people have wide expectations about behaviors. And I'll add that most adults have difficulty groking the 'and/or' model anyhow. 

Where does that leave us? To communicate the 'and' handling of tags, we should have a label such as "Showing results tagged with [tag] and [tag]."

We can do the same for free text search if that's the way we want to go. If we go the or route for freetext, labeling could be:
"Showing items that include any of the words [text] or [text]."

**Comment by dhcole** [comment]
That's super helpful and will add a lot of clarity. Thanks @GailSwanson

**Comment by ultrasaurus** [comment]
In 2016, we removed the groups/projects feature since is wasn't used by any active deployment.
